config/routes.rb
Rails.application.routes.draw do
  resources :welcome, only: [:index]
  resources :schedules, only: [:index, :new, :create]
  resources :visitors, only: [:index, :new, :create]
  resources :informations, only: [:index]
  
  root 'informations#index'

end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :visitors
  accepts_nested_attributes_for :visitors
  scope :between_date, -> (date_range){where(date: date_range)}
  DATE_TYPE = {
    0 => '休日',
    1 => '平日'
  }

  COLORS = {
    'type00' => '黒',
    'type01' => '赤',
    'type02' => '黄',
    'type03' => '緑',
    'type04' => '青',
    'type05' => 'ピンク'
  }

  CONTENTS = [
    "f1_process_",
    "f2_process_",
    "note_"
  ]
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :schedule
  scope :active, -> {where.not('body IS ? OR body = ?', nil, '')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :basic
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def basic
    authenticate_or_request_with_http_basic do |user, pass|
      user == 'ib-factory' && pass == 'ib-factory3131'
    end
  end  
end  

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  layout 'information'
  
  def index
    @notice = Notice.first
    if params[:date].present?
      @today = Date.parse(params[:date])
    else
      @today = Date.today
    end

    two_weeks = @today.weeks_since(2)
    @schedule = Schedule.find_by(date: Date.today)
    @visitors = @schedule.visitors.where.not(body: [nil, '']) if @schedule.present?
    @schedules = Schedule.where(date: (@today..two_weeks))
    render action: :index
  end
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @notice = Notice.first ? Notice.first : Notice.new
    if params[:date]
      @beginning_of_month = Date.parse(params[:date]).beginning_of_month
    else
      @beginning_of_month = Date.today.beginning_of_month
    end
    @end_of_month = @beginning_of_month.end_of_month
    date_range = (@beginning_of_month..@end_of_month)
    @schedules = Schedule.between_date(date_range)
  end
  
  def new
    @notice = Notice.first ? Notice.first : Notice.new
    @schedule = Schedule.find_or_initialize_by(date: params[:date])
    @visitor_title = @schedule.visitor_title.present? ? @schedule.visitor_title : 'ようこそ株式会社アイビーへ'
    if @schedule.date_type.blank?
      if @schedule.date.wday == 0 || HolidayJp.holiday?(@schedule.date)
        @schedule.date_type = 0
      else
        @schedule.date_type = 1
      end      
    end
  end

  def edit
  end

  def create
    @notice = Notice.find_or_initialize_by(id: 1)
    @notice.update(permit_notice_params)
    @schedule = Schedule.find_or_initialize_by(date: params[:schedule][:date])
    @schedule.update(permit_schedule_params)
    redirect_to action: :index, controller: :schedules, date: @schedule.date
  end

  private
  def permit_schedule_params
    params.require(:schedule).permit(
      :date,
      :body,
      :visitor_title,
      :visitor_body,
      :visitor_template,
      :date_type,
      :f1_process_1,
      :f1_process_2,
      :f1_process_3,
      :f1_process_4,
      :f1_process_5,
      :f2_process_1,
      :f2_process_2,
      :f2_process_3,
      :f2_process_4,
      :f2_process_5,
      :f1_process_color_1,
      :f1_process_color_2,
      :f1_process_color_3,
      :f1_process_color_4,
      :f1_process_color_5,
      :f2_process_color_1,
      :f2_process_color_2,
      :f2_process_color_3,
      :f2_process_color_4,
      :f2_process_color_5,
      :note_1,
      :note_2,
      :note_3,
      :note_4,
      :note_5,
      :note_color_1,
      :note_color_2,
      :note_color_3,
      :note_color_4,
      :note_color_5
    )
  end
  
  def permit_information_params
    params.require(:information).permit(:body)
  end

  def permit_visitor_params
    params.require(:visitor).permit(started_at: [], ended_at: [], body: [], template: [], color: [], id: [])
  end

  def permit_notice_params
    params.require(:notice).permit(:body)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

  def new
  end

  def create
    Visitor.create(permit_visitor_params)
  end

  private
  def permit_visitor_params
    params.require(:visitor).permit(:body,:started_at, :ended_at, :template, :color)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'information'
  def index
    if params[:date].present?
      @today = Date.parse(params[:date])
    else
      @today = Date.today
    end
    
    @schedule = Schedule.find_by(date: @today)
    render action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def schedule_calendar(week_length,link=false)
    content_tag :table, class: 'week' do
      head = content_tag :tr do
        concat content_tag(:th, '',class: 'top')
        concat content_tag(:td, '第一工場', class: 'top')
        concat content_tag(:td, '第二工場', class: 'top')
        concat content_tag(:td, '備考', class: 'top topRight')
      end
      concat head
      weeks_table = weeks(week_length).map do |date|
        schedule = @schedules.select{|schedule| schedule.date == date }.first

        if HolidayJp.holiday?(date)
          options = {class: 'holiday'}          
        elsif date.wday == 0
          options = {class: 'holiday'}
        end
        if schedule.present?
          if schedule.date_type == 1
            options = nil
          elsif schedule.date_type == 0
            options = {class: 'holiday'}
          end
        end
        

        content_tag :tr, options do
          concat content_tag(:th, I18n.l(date, format: :day), scope: 'row', class: "calendar_day_#{date.wday}")
          
          f1_process = content_tag(:td) do
            if schedule.present?
              (1..5).each do |i|
                concat content_tag(:span, eval("schedule.f1_process_#{i}"), class: eval("schedule.f1_process_color_#{i}"))
              end
            end
          end
          f2_process = content_tag(:td) do
            if schedule.present?
              (1..5).each do |i|
                concat content_tag(:span, eval("schedule.f2_process_#{i}"), class: eval("schedule.f2_process_color_#{i}"))
              end
            end
          end
          notes = content_tag(:td) do
            if schedule.present?
              (1..5).each do |i|
                concat content_tag(:span, eval("schedule.note_#{i}"), class: eval("schedule.note_color_#{i}"))
              end
            end
          end
          concat f1_process
          concat f2_process
          concat notes
        end
      end.join.html_safe
      concat weeks_table
    end
  end

  def weeks(size)
    current = @today
    last = current.weeks_since(size)
    return (current..last)
  end
  
  def get_date_type(date=false)
    if @schedule.blank?
      if date.wday == 0 || HolidayJp.holiday?(date)
        date_type = 0
      end
    elsif @schedule.date_type.blank?
      puts @schedule.date_type
      if @schedule.date.wday == 0 || HolidayJp.holiday?(@schedule.date)
        date_type = 0
      end
    else
      date_type = @schedule.date_type
    end
    
    return date_type
  end
  
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def select_templates
    template_dir = File.join(Rails.root,'public','img','visitor','*.jpg')
    templates = []
    Dir.glob(template_dir) do |file|
      templates << File.basename(file)
    end
    return templates.sort
  end

  def get_plan(content,num)
    eval("@schedule.#{content}#{num}")
  end
  
  def get_plan_color(content,num)
    eval("@schedule.#{content}color_#{num}")
  end
  
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/informations/index.html.erb
<div class="header clearfix">
  <div class="dateBox">
    <span><%= @today.year %>年</span><br />
    <%= l(@today, format: :schedule) %>
  </div>
  <div class="infoBox">
    <% if @schedule.present?  %>
      <%= simple_format(h(@schedule.body)) %>
    <% else -%>
      本日の予定はありません
    <% end -%>
  </div>
  <div class="scheduleBox">
    <% if @notice.present? %>
      <%= simple_format(h(@notice.body)) %>
    <% else -%>
      本日のお知らせはありません
    <% end -%>
  </div>
  <!-- class "header" -->
</div>
<%= schedule_calendar(2) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>InformationSystem</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id='header'></div>
    <div class="main-container">
      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/information.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>株式会社アイビー</title>
    <% if params[:controller] =~ /welcome/ %>
      <link href="/css/welcome.css" rel="stylesheet" type="text/css" />
    <% else -%>
      <link href="/css/stylesheet.css" rel="stylesheet" type="text/css" />
    <% end -%>
    <script language='javascript'>
      function tm() {
        tm = setInterval("location.reload()",60000);
      }
    </script>
  </head>

  <body onLoad="tm()">
    <a id="top"></a>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/_plan.html.erb
<% if @schedule.body.present? -%>
  <div class='inf-container'>
    <div class="plan_body">
      <%= simple_format(h(@schedule.body)) %>
    </div>
  </div>
<% end -%>

app/views/schedules/_visitors.html.erb
<% if @schedule.visitor_body.present? -%>
  <div class='inf-container'>
    <div class='visitor_body'>
      <%= @schedule.try(:visitor_title) %><br />
      <span><%= simple_format(h(@schedule.visitor_body)) %></span>
    </div>
  </div>
<% end -%>

app/views/schedules/index.html.erb
<h1><%= @beginning_of_month.month %>月のスケジュール一覧</h1>
<%= button_tag '表示切り替え', id: 'switch_inf' %>
<%= link_to '前月',"/schedules?date=#{@beginning_of_month.prev_month}" %>
<%= link_to '今月',"/schedules?date=#{Date.today}" %>
<%= link_to '次月',"/schedules?date=#{@beginning_of_month.next_month}" %>
<p>日付をクリックし、入力画面より入力してください。</p>
        
<table class='schedule_list'>
  <tr>
    <th class='date'>日付</th>
    <th class='holiday'>休日</th>
    <th class='head_1'>第一工場</th>
    <th class='head_2'>第二工場</th>
    <th class='notes'>備考</th>
  </tr>
  <% (@beginning_of_month..@end_of_month).each do |date| %>
    <% @schedule = @schedules.select{|schedule| schedule.date == date}.first %>
    <tr>
      <td class='date'><%= link_to l(date, format: :day), "/schedules/new?date=#{date}" %></td>
      <td class='holiday'><%= Schedule::DATE_TYPE[0] if get_date_type(date)  == 0 %></td>
      <% Schedule::CONTENTS.each do |content| -%>
        <td>
          <% if @schedule.present? %>
            <% if content =~ /process/ %>
              <% if content =~ /f1/ -%>
                <%= render partial: 'plan' %>
              <% else -%>
                <%= render partial: 'visitors' %>
              <% end -%>
            <% end -%>
            <div class='plan-container'>
            <% (1..5).each do |i| -%>
              <% plan = get_plan(content, i) -%>
              <% plan_color = get_plan_color(content, i) -%>
              <% if plan -%>
                <% klass = content =~ /process/ ? 'plan' : '' -%>
                <%= content_tag(:span, plan, class: [plan_color, klass].join(' ')) %>
              <% end -%>
            <% end -%>
            </div>
          <% end -%>
        </td>
      <% end-%>
  <% end -%>
</table>

app/views/schedules/new.html.erb
<%= form_for(@schedule, url: schedules_path, multipart: true, method: :post, ) do |f| %>
  <div class='head'>
    <div class='date'><h2><%= params[:date] %></h2></div>
    <div class='top'>
      <%= link_to '一覧へ戻る', "/schedules/?date=#{params[:date]}" %>
    </div>    
  </div>  
  <br style='clear: both' />
  <%= hidden_field_tag 'schedule[date]', params[:date] %>
  <div class="cont">
    <h3>平日・休日の設定<div class='date_type'><%= select_tag "schedule[date_type]", options_for_select(Schedule::DATE_TYPE.map{|k,v| [v,k]}, @schedule.date_type) %></div></h3>
    <div id="notice">
      <div class='field'>
        <div class='center'>お知らせ&nbsp;<span class='type01' id='notice_error'></span></div>
        <%= text_area_tag 'notice[body]', @notice.body, {rows: 5, cols: 90} %>
      </div>
    </div>
    <div id="plan">
      <div class='field'>
        <div class='center'>本日の予定&nbsp;<span class='type01' id='schedule_error'></span></div>
        <%= text_area_tag 'schedule[body]', @schedule.body, {rows: 5, cols: 90} %>
      </div>
    </div>
  </div>
  <% (1..3).each do |i| %>
    <% if i != 3 %>
      <div class="factory_<%= i %>">
        <div class='center'>第<%= cycle('一','二') %>工場</div>
      <% else -%>
        <div class="notes">
          <div class='center'>備考</div>
    <% end -%>
    <table>
      <tr>
        <th class='left plan'>タイトル</th>
        <th>文字色</th>
      </tr>
      <% (1..5).each do |j| %>
        <tr>
          <% if i != 3 %>
            <td><%= text_field_tag "schedule[f#{i}_process_#{j}]", eval("@schedule.f#{i}_process_#{j}"),size: 70 %></td>
            <td><%= select_tag "schedule[f#{i}_process_color_#{j}]", options_for_select(Schedule::COLORS.map{|k,v| [v,k]}, eval("@schedule.f#{i}_process_color_#{j}")) %></td>
          <% else -%>
            <td><%= text_field_tag "schedule[note_#{j}]", eval("@schedule.note_#{j}"), size: 70 %></td>
            <td><%= select_tag "schedule[note_color_#{j}]", options_for_select(Schedule::COLORS.map{|k,v| [v,k]}, eval("@schedule.note_color_#{j}"))  %></td>
          <% end -%>
        </tr>
      <% end -%><%#= j each end %>
    </table>
    </div>
  <% end -%><%#= i each end %>
  <div class="cont">
    <h3 class="red">来客メッセージの設定</h3>    
    <div class='visitors'>
      <div class='visitor_title'>
        <h4 class='v_title'>来客用タイトル</h4>
        <div><%= text_field_tag 'schedule[visitor_title]', @visitor_title, size: 58 %></div>
      </div>
      <div class="visitor_template">
        <h4 class='v_temp'>来客用背景画像</h4>
        <div><%= select_tag 'schedule[visitor_template]', options_for_select(select_templates,@schedule.visitor_template) %></div>
      </div>
      <table>
        <tr>
          <th class='left'>ご来訪者様&nbsp;<span class='type01' id='visitor_error'></span></th>
        </tr>
        <tr>

          <td><%= text_area_tag 'schedule[visitor_body]', @schedule.visitor_body, {rows: 5, cols: 90} %></td>
        </tr>
        
      </table>
    </div>
    <div class='images'>
      <ul>
        <li><h4 class="images_title">▼予定表イメージ</h4><img src="/img/index_img.jpg"/></li>
        <li><h4 class="images_title">▼来訪者のお知らせイメージ</h4><img src="/img/news_img.jpg"/></li>
      </ul>
    </div>
  </div>  
  <br style='clear: both' />
  <hr />
  <div class='submit'>
    <%= submit_tag '決定' %>
  </div>
<% end -%>

app/views/visitors/index.html.erb
<h1>Visitors#index</h1>
<p>Find me in app/views/visitors/index.html.erb</p>

app/views/visitors/new.html.erb
<h1>Visitors#new</h1>
<p>Find me in app/views/visitors/new.html.erb</p>

app/views/welcome/index.html.erb
<div class="header clearfix">
  <% if @schedule.present? && @schedule.visitor_body.present? %>
    <p><%= @schedule.visitor_title %></p>
  <% else -%>
    <p>ようこそ株式会社アイビーへ</p>
  <% end -%>
  <!-- class "header" -->
</div>
<div>
  <% if @schedule.present? && @schedule.visitor_body %>
    <ul class="company">
      <li><%= simple_format(h(@schedule.visitor_body)) %></li>
    </ul>
  <% end %>
</div>
<style type="text/css" media="screen">
  .wrapper {
  background-image: url("/img/visitor/<%= select_templates.include?(@schedule.try(:visitor_template)) ? @schedule.try(:visitor_template) : "0デフォルト画像.jpg" %>")
  }
</style>